- hosts: ghnodes
  become: true

  tasks:
    - name: Run the container
      docker_container:
        name: nasa-picture
        state: started
        image: "johndavidmarx/hubops:nasa-picture"
        pull: true
        ports:
          - "80:8080"
