kind: Service
apiVersion: v1
metadata:
  name: np-johndavidmarx
spec:
  selector:
    app: np-johndavidmarx
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-johndavidmarx
spec:
  selector:
      matchLabels:
        app: np-johndavidmarx
  replicas: 3
  template:
    metadata:
      labels:
        app: np-johndavidmarx
    spec:
      containers:
        - name: np-johndavidmarx
          image: githubtraining/universe:np-johndavidmarx
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
