- hosts: webservers
  gather_facts: no
  tasks:
    - name: Create desitnation directory on remote webserver
      file:
        path: /var/www/html/reports/{{ghactor}}
        state: directory
    - name: Copy files to remote host
      synchronize:
        src: /home/runner/work/Nasa-Picture/Nasa-Picture/build/reports/tests/test/
        dest: /var/www/html/reports/{{ghactor}}
      become: true
