- hosts: webservers
  gather_facts: no
  tasks:
    - name: Copy files to remote host
      synchronize:
        src: /home/runner/work/Nasa-Picture/Nasa-Picture/build/reports/tests/test/
        dest: /var/www/html/reports/"{{lookup('env','github-actor')}}"
      become: true
