#
# This is an example of a GitHub Actions workflow that performs CI (Continuous Integration) and CD (Continuous Deployment) Functions
#

name: Java CI/CD Pipeline Example

#
# The workflow is launched when any file in any branch is changed
#
on: [push]
jobs:
  build:
#
# This workflow uses an Ubuntu Linux Virtual Machine (the "runner") to perform the workflow steps
#
    runs-on: beefcake

    steps:
#
# The checkout action replicates the repository files into the virtual machine instance
#
    - uses: actions/checkout@v1

#
# The setup-java actions installs the 1.8 version of the Java JDK
#
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

#
# The gradlew wrapper has been installed in the repo and is used to run the gradle build. The first run is to run the unit tests defined in the application
#      
    - name: Run Unit Tests
      run: ./gradlew test
#
# Once the test reports have been produced they are copied to the test-reports folder on the runner instance
#      
    - name: Stage Test Reults
      run: cp build/test-results/test/*.xml test-reports
