name: Java CI With Gradle Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare pem file
      run: gpg --quiet --batch --yes --decrypt --passphrase="$GPGPW" --output marx4universe.pem secrets/marx4universe.pem.gpg
      env:
        GPGPW: ${{secrets.awspassword}}
    - name: Fix Perms on pem
      run: chmod 400 marx4universe.pem
    - name: Access AWS Jump Box
      run: ssh -o StrictHostKeyChecking=no -i marx4universe.pem ubuntu@ec2-18-191-112-1.us-east-2.compute.amazonaws.com /home/ubuntu/playit.sh nasa-picture.yml
      
