name: Java CI

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Prepare pem file
      run: gpg --quiet --batch --yes --decrypt --passphrase="$GPGPW" --output marx4universe.pem secrets/marx4universe.pem.gpg
      env:
        GPGPW: ${{secrets.awspassword}}
        
    - name: Change pem File Permissions
      run: chmod 0400 marx4universe.pem
      
    - name: Run Unit Tests
      run: ./gradlew test
      
    - name: Stage Test Reults
      run: cp build/test-results/test/*.xml test-reports

    - uses: actions/upload-artifact@master
      with:
        name: test-report
        path: test-reports/      
    
    - name: Copy Test Reports To AWS Webserver
      run: ansible-playbook -u ubuntu --private-key=marx4universe.pem -i ansible/inventory.yml --extra-vars "ghactor=${{github.actor}}" ansible/copy-test-reports.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Docker Build
      run: docker build -t nasa-picture .
#    - name: Login To Docker Hub
#      run: docker login -u ${{secrets.dhuser}} -p ${{secrets.dhpassword}}
    - name: Tag Docker Image
      run: docker tag nasa-picture:latest johndavidmarx/hubops:nasa-picture
    - name: Push Image To DockerHub
      run: docker push johndavidmarx/hubops:nasa-picture
     
    - name: Decrypt k8s config credentials
      run: gpg --quiet --batch --yes --decrypt --passphrase="$GPGPW" --output k8s_config secrets/k8s_config.gpg
      env:
        GPGPW: ${{secrets.awspassword}}

    - name: Kubernetes kubectl delete deployment nasa-picture
      run: kubectl delete deployment nasa-picture
      env: 
        KUBECONFIG: k8s_config

    - name: Kubernetes kubectl delete service nasa-picture
      run: kubectl delete service nasa-picture
      env: 
        KUBECONFIG: k8s_config
       
    - name: Kubernetes kubectl create service and application deployment
      run: kubectl create -f kubernetes/nasa-picture.yml
      env: 
        KUBECONFIG: k8s_config

    - name: Kubernetes kubectl get service
      run: kubectl get service
      env: 
        KUBECONFIG: k8s_config
        
    - name: Kubernetes kubectl get deployments
      run: kubectl get deployments
      env: 
        KUBECONFIG: k8s_config

    - name: Kubernetes kubectl get pods
      run: kubectl get pods
      env: 
        KUBECONFIG: k8s_config
