name: Java CI With Gradle Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Prepare pem file
      run: gpg --quiet --batch --yes --decrypt --passphrase="$GPGPW" --output marx4universe.pem secrets/marx4universe.pem.gpg
      env:
        GPGPW: ${{secrets.awspassword}}
    - name: Fix Perms on pem
      run: chmod 400 secrets/marx4universe.pem
    - name: Look
      run: ls -la;cat marx4universe.pem
    - name: Access AWS Jump Box
      run: ssh -i marx4universe.pem ubuntu@ec2-3-15-159-151.us-east-2.compute.amazonaws.com /home/ansible/test.sh
      
