name: Java CI With Gradle Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Inject Token
      run: |
          cat ${{secrets.awspem}} > ansible.pem
          chmod 400 ansible.pem
    - name: Access AWS Jump Box
      run: ssh -i ansible.pem ubuntu@ec2-3-15-159-151.us-east-2.compute.amazonaws.com "pwd"
      
