name: Java CI

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Prepare pem file
      run: gpg --quiet --batch --yes --decrypt --passphrase="$GPGPW" --output marx4universe.pem secrets/marx4universe.pem.gpg
      env:
        GPGPW: ${{secrets.awspassword}}
    - name: Change pem File Permissions
      run: chmod 0400 marx4universe.pem
    - name: Run Unit Tests
      run: ./gradlew test
    - name: pwd
      run: pwd
    - name: Copy Test Reports To AWS Jump Box
      run: ansible-playbook -u ubuntu --private-key=marx4universe.pem -i ansible/inventory.yml ansible/copy-test-reports.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False

    - name: Build with Gradle
      run: ./gradlew build
